### ISSUE TITLE
Cost service: error in the log

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#598] opened 2016-11-02 05:35 UTC
[Add_Terminal.yawl.gz](https://github.com/yawlfoundation/yawl/files/565747/Add_Terminal.yawl.gz)
[AddTerminalCostModel.xml.gz](https://github.com/yawlfoundation/yawl/files/565748/AddTerminalCostModel.xml.gz)
When executing the attached specification for the attached cost model, an error is logged after execution of task ‘Quality_Check’:
![image](https://cloud.githubusercontent.com/assets/14101966/19917781/f30d231e-a111-11e6-8e13-341eb0007f36.png)

**Comment by yawlfoundation** [comment] 2016-11-04 13:44
Can you please post the 'localhost.log' for 2016-11-02? That should contain details about the cause of the problem.

**Comment by a-pika** [comment] 2016-11-08 00:24
[localhost.2016-11-02.log.gz](https://github.com/yawlfoundation/yawl/files/577014/localhost.2016-11-02.log.gz)

**Comment by yawlfoundation** [comment] 2017-01-19 17:33
Fixed in latest update (odd behaviour writing to costservice logon to audit log)

**Closed by yawlfoundation** 2017-01-19 17:33 UTC
