### ISSUE TITLE
Dynamic instance creation for MI composite task

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#578] opened 2016-06-20 04:40 UTC
[MIsubprocess.yawl.gz](https://github.com/yawlfoundation/yawl/files/322720/MIsubprocess.yawl.gz)

When executing the attached specification (‘MIsubprocess.yawl’), ‘New Instance’ button is never enabled; dynamic instance creation is enabled for the MI composite task ‘b’:
![image](https://cloud.githubusercontent.com/assets/14101966/16183411/d2109434-36f4-11e6-86ae-0d563d6f0620.png)
![image](https://cloud.githubusercontent.com/assets/14101966/16183412/da74f7dc-36f4-11e6-99b9-12a403683832.png)

**Comment by yawlfoundation** [comment] 2016-08-08 11:47
duplicate of #323

**Closed by yawlfoundation** 2016-08-08 11:47 UTC
